### PR TITLE
Fix NPE & cfieber's comments

### PR DESCRIPTION
**Pull request by lwander**
Wasn't sure what this meant: https://github.com/spinnaker/scheduled-actions/commit/1ae48abee830f7b8f6778acbabed2a8061c6ea34#commitcomment-16920114

Also, I'm a little nervous about dropping cassandra all together in this branch. Could we keep it and enable Redis in Echo via feature flag?

@cfieber @tomaslin

### CODE REVIEW

**Comment by tomaslin** [comment]
LGTM
I don't feel strongly about either having cassandra or not

**Comment by tomaslin** [comment]
@lwander is this good to merge?

**Comment by lwander** [comment]
Sorry not yet, was side-tracked on other bugs. I just have to add cassandra back as an alternative, so updating this package won't break echo.

**Comment by lwander** [comment]
Good to merge

**Comment by tomaslin** [comment]
LGTM

**Pull request merged**
