### PR TITLE
Make the number of threads in the fixed thread pool match the number …

### PR DESCRIPTION
**Pull request by duftler**
…of unit test cases.

### CODE REVIEW

**Comment by duftler** [comment]
fyi @robzienert 

I _think_ this was the issue with the intermittent Travis failures. The number of threads in the fixed thread pool was too small and I'm thinking the requested jobs were still queued up when the comparison was made in the `when:` clause.

**Comment by duftler** [comment]
Relates to the Travis CI unit test failure on: https://github.com/spinnaker/scheduled-actions/pull/9

**Comment by duftler** [comment]
@lwander PTAL

**Comment by duftler** [comment]
The thread pool size from the test fixture ends up being used to create a `LocalThreadPoolBlockingExecutor` here: https://github.com/spinnaker/scheduled-actions/blob/master/scheduled-actions-core/src/main/java/com/netflix/scheduledactions/ActionsOperator.java#L67

`LocalThreadPoolBlockingExecutor` in turn create a fixed thread pool Executor here: https://github.com/spinnaker/scheduled-actions/blob/master/scheduled-actions-core/src/main/java/com/netflix/scheduledactions/executors/LocalThreadPoolBlockingExecutor.java#L39

As per javadocs (https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Executors.html#newFixedThreadPool(int)), if no capacity remains, this happens: "If additional tasks are submitted when all threads are active, they will wait in the queue until a thread is available."

**Comment by duftler** [comment]
The failure we see intermittently on Travis CI can be consistently provoked locally by shrinking the size of the test fixture thread pool to `1`.

**Comment by lwander** [comment]
Nice catch, LGTM

**Pull request merged**
